version: '3.4'

services:
  aggregatorservice:
    image: aggregatorservice:dev
    container_name: AggregatorService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AggregatorService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_aggregatorservice$
    volumes:
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo\aggregatorservice:/app
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo:/src
      - C:\Users\himanshugarg\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_aggregatorservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_aggregatorservice$ \"bin/Debug/netcoreapp3.1/AggregatorService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  customerapi:
    image: customerapi:dev
    container_name: CustomerApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CustomerApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_customerapi$
    volumes:
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo\CustomerApi:/app
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo:/src
      - C:\Users\himanshugarg\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_customerapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_customerapi$ \"bin/Debug/netcoreapp3.1/CustomerApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  orderapi:
    image: orderapi:dev
    container_name: OrderApi
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "OrderApi"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_orderapi$
    volumes:
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo\OrderApi:/app
      - C:\Users\himanshugarg\Desktop\Dot Net JaegerDemo\JaegerDemo:/src
      - C:\Users\himanshugarg\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_orderapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_orderapi$ \"bin/Debug/netcoreapp3.1/OrderApi.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
